# File: .github/workflows/finish_release.yml
name: Finish Gitflow Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  finish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-flow
          npm install -g auto-changelog

      - name: Extract version
        id: extract
        run: |
          VERSION=$(git log -1 --pretty=format:%s | sed -E 's/^Release[[:space:]]+//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Initialize Gitflow
        run: git flow init -d

      - name: Finish release
        run: git flow release finish -m "${{ steps.extract.outputs.version }} release" "${{ steps.extract.outputs.version }}"

      - name: Push main, develop, and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
          git push origin develop
          git push origin --tags
